# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Stop previous instance (if exists)
        if: always()
        run: sudo systemctl stop hotel-admin-app || true

      - name: Create environment file for systemd service
        run: |
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" | sudo tee /etc/hotel-admin-app.env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" | sudo tee -a /etc/hotel-admin-app.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee -a /etc/hotel-admin-app.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" | sudo tee -a /etc/hotel-admin-app.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" | sudo tee -a /etc/hotel-admin-app.env
          echo "SSL_PASSWORD=${{ secrets.SSL_PASSWORD }}" | sudo tee -a /etc/hotel-admin-app.env
          sudo chmod 600 /etc/hotel-admin-app.env

      - name: Build with Maven
        run: mvn --file /home/ec2-user/actions-runner/_work/HotelRegistar/HotelRegistar/userService/pom.xml clean install -DskipTests

      - name: Start the new version
        run: sudo systemctl start hotel-admin-app

      - name: Wait for the application to start
        id: wait-for-app
        run: |
          retries=0
          max_retries=20  # Adjust the number of retries based on your application's startup time
          while [ $retries -lt $max_retries ]; do
            if curl -k --output /dev/null --silent --head --fail https://localhost:9000/actuator/health; then
              echo "Application started successfully."
              exit 0
            fi
            echo "Waiting for application to start... Attempt $((retries + 1))"
            retries=$((retries + 1))
            sleep 10s
          done
          echo "Application startup timed out."
          exit 1
